version: "3"
services:
  app:
    image: ktor-sample:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:12.2
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports: 
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
    driver: local
